development:
  host: localhost
  database: gradebook_development

test:
  host: localhost
  database: gradebook_test

# set these environment variables on your prod server
production:
  host: localhost
  port: 27017
  username: root
  password: sagetlick
  database: wadedb
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
